# Generated by Django 4.1.1 on 2022-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_option_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='option',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/option', verbose_name='Imagen'),
        ),
    ]
