# Generated by Django 4.1.1 on 2022-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_option_price_alter_option_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='img',
        ),
    ]
