# Generated by Django 4.1.1 on 2022-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_remove_option_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Recomendado'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
