# Generated by Django 4.1.1 on 2022-09-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
        ('option', '0005_option_recommended_alter_option_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Comida', 'verbose_name_plural': 'Comidas'},
        ),
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoria'),
        ),
    ]
